let f = 20.5;
let b = true;
let s = 'Hà Nội';
let i = 10;
document.write('i = ' + i);
document.write('<br/>');
document.write('f = ' + f);
document.write('<br/>');
document.write('b = ' + b);
document.write('<br/>');
document.write('s = ' + s);